spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://www.liyanxing.top:3306/db_account_studyuser?serverTimezone=Asia/Shanghai
        username: leeyx
        password: leeyx0109
    jackson:
        serialization:
          fail-on-empty-beans: false
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: Ov23liJwdFOZTOGuzPEK
                        client-secret: c3945cf423603e82eb4deff87f185fc3fe5b4783